name: Plan changes to the Cloudflare

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_cloudflare_api_token: '${{ secrets.CLOUDFLARE_API_TOKEN }}'
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan
